## YAML Template.
Enquete:
  fields:
    id:
      name: Id
      type: integer
      grid: false
      required: false
      search: false
      detail: true
    pergunta:
      name: Pergunta
      type: string
      size: 80
      maxlength: 40
      grid: true
      form: true
      required: true
      search: true   
      detail: true 
    ativa:
      name: Ativa
      type: select
      size: 50
      grid: true
      form: true
      required: true
      search: true   
      detail: true
      options: S=>Sim,N=>NÃ£o
    resp1:
      name: Resposta 01
      type: string
      size: 50
      maxlength: 25
      grid: false
      form: true
      required: false
      search: false   
      detail: true
    resp2:
      name: Resposta 02
      type: string
      size: 50
      maxlength: 25
      grid: false
      form: true
      required: false
      search: false   
      detail: true
    resp3:
      name: Resposta 03
      type: string
      size: 50
      maxlength: 25
      grid: false
      form: true
      required: false
      search: false   
      detail: true
    resp4:
      name: Resposta 04
      type: string
      size: 50
      maxlength: 25
      grid: false
      form: true
      required: false
      search: false   
      detail: true
    endata:
      name: Data de Cadastro
      type: date
      grid: true
      search: false
      auto: true
      saveFunction: getActualDate
      listFunction: convertDateSQLToDateBRExtense
      updatable: false
      detail: true
  controlClass: GenericCtrl
  viewFile: viewDefault
  formFile: formDefault
  showAddButton: true
  showEditButton: true
  showDeleteButton: true
  orderBy: ativa DESC, endata DESC

  