## YAML Template.
Ganhador:
  fields:
    id:
      name: Id
      type: integer
      grid: false
      required: false
      search: false
      detail: true
    dtSorteio:
      name: Data do sorteio
      type: date
      grid: true
      form: false
      required: false
      search: false
      auto: true
      listFunction: convertDateSQLToDateBRExtense
      detail: true
    login:
      name: Sorteado por
      type: string
      size: 80
      maxlength: 60
      grid: true
      form: true
      required: true
      search: true   
      detail: true
    nome:
      name: Nome
      type: string
      size: 80
      maxlength: 60
      grid: true
      form: true
      required: true
      search: true   
      detail: true
    nascimento:
      name: Data de Nascimento
      type: date
      grid: true
      form: false
      required: false
      search: false
      auto: true
      listFunction: convertDateSQLToDateBRExtense
      detail: true
    telefone:
      name: Telefone
      type: string
      size: 13
      maxlength: 14
      grid: true
      form: true
      required: true
      search: true   
      detail: true
      mask: (99)99999-9999
    cidade:
      name: Cidade
      type: string
      size: 80
      maxlength: 50
      grid: false
      form: true
      required: true
      search: true   
      detail: true  
    bairro:
      name: Bairro
      type: string
      size: 80
      maxlength: 50
      grid: false
      form: true
      required: false
      search: true   
      detail: true
    mensagem:
      name: Mensagem
      type: string
      size: 10
      maxlength: 355
      grid: false
      form: true
      required: false
      search: true   
      detail: true
  controlClass: GenericCtrl
  viewFile: viewDefault
  formFile: formDefault
  showAddButton: false
  showEditButton: true
  showDeleteButton: false
  orderBy: dtSorteio DESC

  