## YAML Template.
Locutor:
  fields:
    id:
      name: Id
      type: integer
      grid: false
      required: false
      search: false
      detail: true
    nome:
      name: Nome
      type: string
      size: 80
      maxlength: 60
      grid: true
      form: true
      required: true
      search: true   
      detail: true
    nascimento:
      name: Data de Nascimento
      type: date
      grid: true
      form: true
      required: true
      search: false
      formFunction: convertDateSQLtoDateBR
      saveFunction: convertDateBRtoDateSQL
      listFunction: convertDateSQLToDateBRExtense
      detail: true
    cidade:
      name: Cidade Natal
      type: string
      size: 80
      maxlength: 50
      grid: true
      form: true
      required: true
      search: true   
      detail: true
    profissao:
      name: Profiss√£o
      type: string
      size: 80
      maxlength: 100
      grid: true
      form: true
      required: true
      search: true   
      detail: true
    imagem:
      name: Imagem
      required: false
      type: image
      grid: false
      form: true
      search: false  
      detail: true
  uploads:
    folder: locutor
  images:
    Capa:
      width: 100
      height: 116
  controlClass: GenericCtrl
  viewFile: viewDefault
  formFile: formDefault
  showAddButton: true
  showEditButton: true
  showDeleteButton: true
  orderBy: nome ASC

  