## YAML Template.
Mural:
  fields:
    id:
      name: Id
      type: integer
      grid: false
      required: false
      search: false
      detail: true
    titulo:
      name: Título
      type: string
      size: 80
      maxlength: 55
      grid: true
      form: true
      required: true
      search: true
      detail: true
      strong: true
    descricao:
      name: Descrição
      type: string
      size: 80
      maxlength: 70
      grid: false
      form: true
      required: true
      search: true
      detail: true
      strong: true
    link:
      name: link
      type: string
      size: 80
      maxlength: 100
      form: true
      required: false
      detail: true
      strong: true
    status:
      name: Mural Ativo
      type: select
      size: 80
      grid: true
      form: true
      required: true
      search: true
      detail: true
      options: S=>Sim, N=>Não
    imagem:
      name: Imagem
      type: image
      grid: false
      form: true
      search: false  
      detail: true
  uploads:
    folder: mural
  images:
    Capa:
      width: 500
      height: 275
  searchLetterColumn: titulo
  controlClass: GenericCtrl
  showEditButton: true
  showDeleteButton: true
  showAddButton: true
  viewFile: viewDefault
  formFile: formDefault
  orderBy: status DESC

  