## YAML Template.
Noticia:
  fields:
    id:
      name: Id
      type: integer
      grid: false
      required: false
      search: false
      detail: true
    titulo:
      name: TÃ­tulo
      type: string
      size: 80
      maxlength: 140
      grid: true
      form: true
      required: true
      search: true
      detail: true
      strong: true
    legenda:
      name: Legenda
      type: string
      size: 80
      maxlength: 100
      form: true
      required: false
      search: false
      detail: false
      strong: true
    descricao:
      name: Descricao
      type: text
      editor: true
      form: true
      required: true
      strong: true
    notData:
      name: Data
      type: date
      grid: true
      form: true
      required: true
      search: false
      formFunction: convertDateSQLtoDateBR
      saveFunction: convertDateBRtoDateSQL
      listFunction: convertDateSQLToDateBRExtense
      detail: true
    imagem:
      name: Imagem
      type: image
      grid: false
      form: true
      search: false  
      detail: true
  uploads:
    folder: noticias
  images:
    Capa:
      width: 100
      height: 60
    Interna:
      width: 500
      height: 275
    Listagem:
      width: 100
      height: 130
  searchLetterColumn: titulo
  controlClass: GenericCtrl
  showEditButton: true
  showDeleteButton: true
  showAddButton: true
  viewFile: viewDefault
  formFile: formDefault
  orderBy: id DESC

  